source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod 'SwiftyJSON', :git => "https://github.com/orta/SwiftyJSON", :branch => "podspec"
pod 'Alamofire', :git => "https://github.com/mrackwitz/Alamofire.git", :branch => "podspec"
pod 'AFNetworking'
